#!/bin/bash
# Start the application server on any port

PORT=$1

export ROOT_URL=https://hexmap.sdsc.edu:$PORT
export MONGO_URL=mongodb://localhost:27017/$PORT
mv /data/$PORT.log /data/$PORT.prev.log
cd /data/$PORT
/data/home/hexmap/.meteor/meteor --port $PORT &> /data/$PORT.log
