#!/bin/bash
# Start the mongoDb daemon

PORT=27000
DIR=/cluster/home/swat/hexmap
MONGOPATH=/cluster/home/swat/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin

touch $DIR/db.log
mv $DIR/db.log $DIR/db.prev.log
$MONGOPATH/mongod \
        --bind_ip 127.0.0.1 \
        --port $PORT \
        --dbpath $DIR/db \
        &> $DIR/db.log &
