#!/bin/bash
# Start a dev server on port 8113

PORT=8113
HTTPS_PORT=8112
DIR=/cluster/home/swat/hexmap
DB_PORT=27000
METEORPATH=/cluster/home/swat/.meteor

export ROOT_URL=https://tumormap.ucsc.edu:$HTTPS_PORT
export MONGO_URL=mongodb://localhost:$DB_PORT/$PORT
touch $DIR/$PORT.log
mv $DIR/$PORT.log $DIR/$PORT.prev.log
cd $DIR/$PORT
$METEORPATH/meteor --port $PORT &> $DIR/$PORT.log &
