#!/bin/bash
# Start the hex server on CIRM

PORT=8113        # Port on which the server listens
HTTPS_PORT=8113  # Https proxy port if using https, otherwise the same as PORT
DB_PORT=28113    # Port on which the database listens
HEXMAP=/data/hexmap/server     # Directory of this script, just above the www directory
METEOR=/pod/home/swat/.meteor  # the meteor installation
export ROOT_URL=http://cirm-01.pod:$HTTPS_PORT # User's view of the URL

export MONGO_URL=mongodb://localhost:$DB_PORT
touch $HEXMAP/www.log
mv $HEXMAP/www.log $HEXMAP/www.prev.log
cd $HEXMAP/www
$METEOR/meteor --port $PORT --settings $HEXMAP/settings.json &> $HEXMAP/www.log &
