#!/bin/bash
# Start the https server on production

HEXMAP=/data
NODE_BIN=/data/home/hexmap/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin

touch $HEXMAP/https.log
mv $HEXMAP/https.log $HEXMAP/https.prev.log
$NODE_BIN/node $HEXMAP/https/https.js &> $HEXMAP/https.log &
