#!/bin/bash
# Start the http server on production

HEXMAP=/data
NODE_BIN=/data/home/hexmap/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin

touch $HEXMAP/http.log
mv $HEXMAP/http.log $HEXMAP/http.prev.log
$NODE_BIN/node $HEXMAP/http/http.js &> $HEXMAP/http.log &
