#!/bin/bash
# For https, set below to "true" and change
# the environment variables inside the if statement.
# For HTTP, change the environment varibles in the else statement.
USING_HTTPS=false
#USING_HTTPS=true
if [  "$USING_HTTPS" = true ]; then
    # Paths to https certs.
    export KEY=/data/certs/hexdev.key
    export CERT=/data/certs/hexdev.crt
    export CHAIN=/data/certs/chain.crt

    # Port for HTTP redirect
    export HTTP_PORT=8221
    # Port HTTPS uses.
    export HTTPS_PORT=8222
    # The port the meteor app uses.
    export PORT=8223/Users/swat/dev/hexagram
    # The URL to which the https proxy redirects.
    export METEOR_URL=http://hexdev.sdsc.edu:$PORT
    # The URL exposed to the user.
    export URL_BASE=https://hexdev.sdsc.edu:$HTTPS_PORT

else
    # For http
    export PORT=8222
    export URL_BASE=http://hexmap-new.sdsc.edu:$PORT
    #export URL_BASE=https://hexmap-new.sdsc.edu:$PORT
fi

# Run in background, BACK, or foreground, FORE.
export BACK_OR_FOREGROUND=BACK

# Bundled deployment or unbundled?
export BUNDLED=false
#export BUNDLED=true
if [  "$BUNDLED" == false ]; then
    # Path to your meteor.
    export METEOR_PATH=$HOME/.meteor/meteor
    export SERVER_DIR=$HEXMAP/www/private/
fi

# Meteor settings.json variables.
export ADMIN_EMAIL=swat@soe.ucsc.edu
export DEV=true
export HUB_URL=https://hexcalc.ucsc.edu:8442
# Below paths/require/the/trailing/slash/.
export VIEW_DIR=/hive/groups/hexmap/dev/data/view/

# Mongo db.
DB_NAME=8111
DB_PORT=28223
export MONGO_BIN=$HEXMAP/packages/mongodb/bin
export MONGO_URL=mongodb://localhost:$DB_PORT/$DB_NAME

export NODE_BIN=$HEXMAP/packages/node/bin
export ROOT_URL=$URL_BASE

