#!/bin/bash
# Run a test after setting the path

if [ $# -eq 0 ]; then
    echo "one argument is needed like this:"
    echo "  all tests: run all (all except for hub tests)"
    echo "  hub tests: run hub"
    echo "   one file: run test_stats"
    echo "   one test: run test_stats.TestStats.test_stats"
    exit 1
fi
# Note: the below are currently order-dependent due to issues with parallel code
ALL=( \
    test_similarity \
    test_layoutBasic \
    test_stats \
)
PARALLEL_CHALLENGED=( \
    test_dynLayoutAware \
    test_sim6Layout \
)
HUB=( \
    hub_web_tests \
    Nof1_web_tests \
)

# these need fixing up:
    #test_createMapUi \
    #test_http \
    #test_noincludesingletons \
    #test_queryOverlayNodes \
    #test_remoteCalc \

export PYTHONPATH=$(pwd)/../../www/server:$(pwd)/../../hub:./
TO_RUN=($1)
if [ $1 == 'all' ]
    then TO_RUN="${ALL[@]}"
elif [ $1 == 'hub' ]
    then TO_RUN="${HUB[@]}"

fi

# Run our well-behaved tests in parallel
python2.7 -m unittest $TO_RUN

# Run our parallel-challenged tests independently
if [ $1 == 'all' ]
    then
    echo Running parallel-challenged tests independently
    for TEST in "${PARALLEL_CHALLENGED[@]}"
    do
        python2.7 $TEST.py
    done
fi
