#!/usr/bin/env bash

#script runs all three test_mcr scripts
# they could not be run together for an unknown reason,
# that likely has to do with the parallel processing going 
# on in both layout.py and the unitTesting.. (?)
export PYTHONPATH=$(pwd)/../../www/server
 
echo testing results of mcr data and full genomic entry 
python2.7 test_mcr_raw.py 
echo testing results of mcr data and full similarity entry 
python2.7 test_mcr_full.py
echo testing results of mcr data and top6 entry 
python2.7 test_mcr_top6.py
echo testing layout and non layout stats test
python2.7 test_stats.py
echo testing compute_similarities output
python2.7 test_createMapScripts.py
