#!/bin/bash 

#simple test to make sure there aren't any errors when running layout.py from bash
# TODO: more automatic testing method. Currently spits out a list of file names
# and an ls of the output dir and hopes the user will check if they are the same.
# 

IN=createMapIn
OUT=createMapOut

rm -rf $OUT/$PROJ
mkdir -p $OUT/$PROJ

python2.7 ../../www/server/layout.py \
    --similarity $IN/mcr.top6.tab \
    --names mRNA \
    --colormaps $IN//mcrchopra.colormaps.tab \
    --directory $OUT

echo files on either line should match:
echo assignments0.tab  colormaps.tab  fake_layer.tab  hexNames.tab  Layer_Data_Types.tab  layouts.tab  log  matrices.tab  matrix_0.tab  neighbors_0.tab  xyPreSquiggle_0.tab
ls $OUT
