#!/usr/bin/env bash


 # Run a test after setting the path
 # Usage:
 #     run test_stats
 #     run test_stats.TestStats.test_stats

 export PYTHONPATH=$(pwd)/../../www/server
 python2.7 test_stats.py 
