#!/bin/bash
# Start the http server on development

HEXMAP=/cluster/home/swat/hexmap
NODE_BIN=/cluster/home/swat/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin

touch $HEXMAP/http.log
mv $HEXMAP/http.log $HEXMAP/http.prev.log
$NODE_BIN/node $HEXMAP/http/http.js &> $HEXMAP/http.log &
