#!/bin/bash
# Start the hex server on development

PORT=8113        # Port on which the server listens
HTTPS_PORT=8112  # Https proxy port if using https, otherwise the same as PORT
DB_PORT=28113    # Port on which the database listens
HEXMAP=/cluster/home/swat/hexmap   # Directory of this script, just above the www directory
METEOR=/cluster/home/swat/.meteor  # the meteor installation
export ROOT_URL=https://tumormap.ucsc.edu:$HTTPS_PORT # User's view of the URL

export MONGO_URL=mongodb://localhost:$DB_PORT/8111
touch $HEXMAP/www.log
mv $HEXMAP/www.log $HEXMAP/www.prev.log
cd $HEXMAP/www
$METEOR/meteor --port $PORT --settings $HEXMAP/settings.json &> $HEXMAP/www.log &
